name: Continuous Integration

on:
  pull_request:
  merge_group:
  push:
    branches: [master, dev]

jobs:
  msrv:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cargo-cmd:
          - build --all-features
          - build --no-default-features
    steps:
      - uses: actions/checkout@v4
      - name: Get current MSRV from Cargo.toml
        id: current_msrv
        run: |
          msrv=$(cat testcontainers/Cargo.toml | grep rust-version | sed 's/.* = "//; s/"//')
          echo "::set-output name=msrv::$msrv"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{steps.current_msrv.outputs.msrv}}
      - uses: Swatinem/rust-cache@v2.7.3
      - run: cargo ${{ matrix['cargo-cmd'] }}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cargo-cmd:
          - test --all-features
          - test --no-default-features
    steps:
      - uses: actions/checkout@v4
      - name: Enable Docker Remote API on Localhost
        shell: bash
        run: |
          sudo mkdir -p /etc/systemd/system/docker.service.d/
          sudo cp ./.github/docker.override.conf /etc/systemd/system/docker.service.d/override.conf
          sudo systemctl daemon-reload
          sudo systemctl restart docker
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2.7.3
      - run: cargo ${{ matrix['cargo-cmd'] }}

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.67
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2.7.3
      - run: cargo clippy --all-targets -- -D warnings
