name: Nightly
on: push
jobs:
  nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v2.7.3
      - run: cargo test
  nightly-lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v2.7.3
      - run: cargo clippy --all-targets -- -D warnings
